#Use for non standard cosmetic tag. Will not be inherited in civil war.
TAG_LIST = {"USoE", "SOV_USSR"}


for TAG in TAG_LIST:
    print("	#"+TAG)
    print("	"+TAG+"_reset_flag = {")
    print("		icon = GFX_decision_generic_form_nation")
    print("		cost = 0")
    print("		ai_will_do = { factor = 1}")
    print("		allowed = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("		visible = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("			has_elections = yes")
    print("		}")
    print("		complete_effect = {")
    print('			log = "[GetDateText]: [Root.GetName]: Decision '+TAG+'_reset_flag"')
    print("			set_cosmetic_tag = "+TAG)
    print("			custom_effect_tooltip = tooltip_change_flag")
    print("		}")
    print("	}")
    print("")
          
    print("	"+TAG+"_Autocracy_flag = {")
    print("		icon = GFX_decision_generic_form_nation")
    print("		cost = 0")
    print("		ai_will_do = { factor = 1}")
    print("		allowed = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("		visible = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("			has_elections = no")
    print("			OR = {")
    print("				has_country_leader_with_trait = western_Western_Autocracy")
    print("				has_country_leader_with_trait = emerging_Autocracy")
    print("				has_country_leader_with_trait = neutrality_Neutral_Autocracy")
    print("				has_country_leader_with_trait = nationalist_Nat_Autocracy")
    print("			}")
    print("		}")
    print("		complete_effect = {")
    print('			log = "[GetDateText]: [Root.GetName]: Decision '+TAG+'_Autocracy_flag"')
    print("			set_cosmetic_tag = "+TAG+"_AUTH")
    print("			custom_effect_tooltip = tooltip_change_flag")
    print("		}")
    print("	}")
    print("")
	
    print("	"+TAG+"_Special_flag = {")
    print("		icon = GFX_decision_generic_form_nation")
    print("		cost = 0")
    print("		ai_will_do = { factor = 1}")
    print("		allowed = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("		visible = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			}")
    print("			has_elections = no")
    print("			OR = {")
    print("				has_country_leader_with_trait = salafist_Kingdom")
    print("				has_country_leader_with_trait = nationalist_Monarchist")			
    print("				has_country_leader_with_trait = emerging_Communist-State")
    print("				has_country_leader_with_trait = neutrality_Neutral_Communism")
    print("			}")
    print("		}")
    print("		complete_effect = {")
    print('			log = "[GetDateText]: [Root.GetName]: Decision '+TAG+'_Special_flag"')
    print("			set_cosmetic_tag = "+TAG+"_AUTH_S")
    print("			custom_effect_tooltip = tooltip_change_flag")
    print("		}")
    print("	}")
    print("")
	
    print("	"+TAG+"_More_Special_flag = {")
    print("		icon = GFX_decision_generic_form_nation")
    print("		cost = 0")
    print("		ai_will_do = { factor = 1}")
    print("		allowed = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("				has_cosmetic_tag = "+TAG+"_REB")
    print("				has_cosmetic_tag = "+TAG+"_REB_S")
    print("			}")
    print("		visible = {")
    print("			OR = {")
    print("				has_cosmetic_tag = "+TAG)
    print("				has_cosmetic_tag = "+TAG+"_AUTH")
    print("				has_cosmetic_tag = "+TAG+"_AUTH_S")
    print("			}")
    print("			has_elections = no")
    print("			OR = {")
    print("				has_country_leader_with_trait = nationalist_Nat_Fascism")
    print("				has_country_leader_with_trait = emerging_Vilayat_e_Faqih")
    print("				has_country_leader_with_trait = emerging_Mod_Vilayat_e_Faqih")
    print("				has_country_leader_with_trait = salafist_Caliphate")
    print("			}")
    print("		}")
    print("		complete_effect = {")
    print('			log = "[GetDateText]: [Root.GetName]: Decision '+TAG+'_More_Special_flag"')
    print("			set_cosmetic_tag = "+TAG+"_AUTH_SS")
    print("			custom_effect_tooltip = tooltip_change_flag")
    print("		}")
    print("	}")
    print("")
